### PR TITLE
Higher-level updates for pybids

### PR DESCRIPTION
**Pull request by adelavega**
WIP Continuing PR for changes to the higher levels

### CODE REVIEW

**Comment by adelavega** [comment]
@effigies this is ready for review. Second level models are successfully being fit.

What is needed now is for the workflow to dynamically generate levels for models with more than 2 levels (which is necessary for the majority of models we'll run, with more than 1 run per subject)

**Comment by effigies** [comment]
This breaks for me:

```
Exception: Subnodes of node: l2_model failed:
Subnode 0 failed
Error: Traceback (most recent call last):

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 99, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 511, in run
    runtime = self._run_interface(runtime)

  File "/src/fitlins/fitlins/interfaces/nistats.py", line 173, in _run_interface
    model.fit(input, design_matrix=design_matrix)

  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nistats/second_level_model.py", line 170, in fit
    raise ValueError('A second level model requires a list with at'

ValueError: A second level model requires a list with atleast two first level models or niimgs
```

**Comment by effigies** [comment]
Ah, I see. I'm using a three-level model. I'll switch to a dataset that only has two levels.

**Comment by effigies** [comment]
By removing the session-level step I get:

```
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 48, in run
    node.run(updatehash=updatehash)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 410, in run
    cached, updated = self.is_cached()
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 296, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1048, in _get_hashval
    self._check_iterfield()
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1214, in _check_iterfield
    "in iterfields.") % iterfield)
ValueError: Input contrast_info was not set but it is listed in iterfields.
```

**Comment by effigies** [comment]
Oh, that's because I was trying to do an autocontrast on a contrast that no longer existed.

At least it's a good demonstration that our error messages are terrible...

**Comment by effigies** [comment]
Okay. This works. I might make some cleanups in my branch, but I'm happy to merge this and move on.

**Pull request merged**
